DROP TABLE IF EXISTS RENTAL_ITEM CASCADE;
DROP TABLE IF EXISTS RENTAL CASCADE;
DROP TABLE IF EXISTS TRACK CASCADE;
DROP TABLE IF EXISTS GENRE CASCADE;
DROP TABLE IF EXISTS ALBUM CASCADE;
DROP TABLE IF EXISTS ARTIST CASCADE;
DROP TABLE IF EXISTS CUSTOMER CASCADE;

CREATE TABLE ARTIST (
    artist_id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    country VARCHAR(100)
);

CREATE TABLE ALBUM (
    album_id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    release_year INTEGER,
    artist_id INTEGER NOT NULL REFERENCES ARTIST(artist_id) ON DELETE CASCADE
);

CREATE TABLE GENRE (
    genre_id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE TRACK (
    track_id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    duration INTEGER CHECK (duration > 0),
    rental_price NUMERIC(10, 2) NOT NULL,
    album_id INTEGER REFERENCES ALBUM(album_id) ON DELETE SET NULL,
    genre_id INTEGER REFERENCES GENRE(genre_id) ON DELETE SET NULL
);

CREATE TABLE CUSTOMER (
    customer_id SERIAL PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE
);

CREATE TABLE RENTAL (
    rental_id SERIAL PRIMARY KEY,
    start_date DATE DEFAULT CURRENT_DATE,
    end_date DATE NOT NULL,
    customer_id INTEGER NOT NULL REFERENCES CUSTOMER(customer_id) ON DELETE CASCADE,
    CONSTRAINT check_dates CHECK (end_date >= start_date)
);

CREATE TABLE RENTAL_ITEM (
    rental_id INTEGER NOT NULL REFERENCES RENTAL(rental_id) ON DELETE CASCADE,
    track_id INTEGER NOT NULL REFERENCES TRACK(track_id) ON DELETE CASCADE,
    PRIMARY KEY (rental_id, track_id)
);
